"""
Load and validate approved Markdown policy documents for Phase 2.

This module is deliberately independent of Ollama, Chroma, LangChain, and the
application settings object.  It can therefore be unit-tested with temporary
files and reused by policy validation, ingestion, and rebuild scripts.

Security and integrity guarantees:

- YAML front matter is parsed with ``yaml.safe_load``.
- Required metadata is validated and normalized.
- Only approved fictional-prototype policies are accepted.
- YAML-supplied filesystem/path fields are rejected.
- ``source_file`` is always derived from ``Path.name``.
- ``source_hash`` is calculated from the complete normalized policy source.
- Duplicate ``document_id`` values are rejected when files are loaded together.
- Absolute filesystem paths are never included in stored policy metadata.
"""

from __future__ import annotations

import hashlib
import re
from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from types import MappingProxyType
from typing import Any

import yaml

REQUIRED_METADATA_FIELDS: tuple[str, ...] = (
    "document_id",
    "title",
    "version",
    "effective_date",
    "review_date",
    "owner",
    "status",
    "product",
    "policy_type",
    "jurisdiction",
)

# These fields are generated by application code and must never be trusted when
# supplied by policy YAML.
DERIVED_METADATA_FIELDS: frozenset[str] = frozenset(
    {
        "source_file",
        "source_hash",
        "content_hash",
        "chunk_id",
        "chunk_index",
        "section_path",
        "header_1",
        "header_2",
        "header_3",
    }
)

# Explicitly rejected path aliases.  The suffix checks in
# ``_is_forbidden_metadata_key`` catch additional path-like variants.
FORBIDDEN_PATH_FIELDS: frozenset[str] = frozenset(
    {
        "path",
        "file",
        "filename",
        "filepath",
        "directory",
        "folder",
        "source",
        "source_path",
        "source_filepath",
        "absolute_path",
        "local_path",
    }
)

DOCUMENT_ID_PATTERN = re.compile(r"^[a-z][a-z0-9_]*$")
SHA256_PATTERN = re.compile(r"^[0-9a-f]{64}$")


class PolicyValidationError(ValueError):
    """Raised when a policy file or policy collection is invalid."""


class DuplicatePolicyDocumentError(PolicyValidationError):
    """Raised when two policy files declare the same document ID."""


@dataclass(frozen=True, slots=True)
class PolicyDocument:
    """A validated policy document ready for chunking and ingestion.

    ``source_path`` is retained for local processing only.  It is intentionally
    excluded from ``storage_metadata`` so absolute local paths cannot enter
    Chroma or prompts.
    """

    source_path: Path = field(repr=False)
    body: str = field(repr=False)
    metadata: Mapping[str, str]
    normalized_source: str = field(repr=False)

    @property
    def document_id(self) -> str:
        """Return the policy's stable document identifier."""

        return self.metadata["document_id"]

    @property
    def source_file(self) -> str:
        """Return the safe basename derived from the actual source path."""

        return self.metadata["source_file"]

    @property
    def source_hash(self) -> str:
        """Return the SHA-256 hash of the complete normalized source file."""

        return self.metadata["source_hash"]

    def storage_metadata(self) -> dict[str, str]:
        """Return a mutable copy safe to store with policy chunks."""

        return dict(self.metadata)


# ---------------------------------------------------------------------------
# Text and hash normalization
# ---------------------------------------------------------------------------


def normalize_date(value: object) -> str:
    """Normalize a YAML date-like value to text.

    PyYAML may deserialize an unquoted ISO date into ``datetime.date``.  The
    Phase 2 policy format still recommends quoted dates, but this helper keeps
    validation deterministic for either representation.
    """

    if hasattr(value, "isoformat"):
        isoformat = getattr(value, "isoformat")
        if callable(isoformat):
            return str(isoformat()).strip()

    return str(value).strip()


def normalize_policy_source(text: str) -> str:
    """Normalize a complete policy file before parsing and hashing.

    Normalization removes an optional UTF-8 BOM, converts all line endings to
    LF, removes trailing spaces and tabs from each line, and ensures one final
    newline.  Meaningful internal blank lines and Markdown structure remain.
    """

    if not isinstance(text, str):
        raise TypeError("Policy source must be a string.")

    normalized = text.removeprefix("\ufeff")
    normalized = normalized.replace("\r\n", "\n").replace("\r", "\n")
    normalized = "\n".join(line.rstrip(" \t") for line in normalized.split("\n"))
    normalized = normalized.rstrip("\n") + "\n"

    return normalized


def normalize_chunk_content(content: str) -> str:
    """Normalize one future retrieval chunk before calculating content_hash."""

    if not isinstance(content, str):
        raise TypeError("Chunk content must be a string.")

    normalized = content.replace("\r\n", "\n").replace("\r", "\n")
    normalized = "\n".join(line.rstrip(" \t") for line in normalized.split("\n"))
    normalized = normalized.strip()

    if not normalized:
        raise PolicyValidationError("Cannot hash empty policy chunk content.")

    return normalized


def _sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def compute_source_hash(normalized_source: str) -> str:
    """Hash a complete normalized policy source file."""

    if not isinstance(normalized_source, str):
        raise TypeError("Normalized policy source must be a string.")

    if not normalized_source.strip():
        raise PolicyValidationError("Cannot hash an empty policy source.")

    return _sha256_text(normalized_source)


def compute_content_hash(content: str) -> str:
    """Hash one normalized final chunk.

    This helper is provided for Steps 13 and 14.  ``content_hash`` must remain
    separate from the full-file ``source_hash``.
    """

    return _sha256_text(normalize_chunk_content(content))


# ---------------------------------------------------------------------------
# Front-matter parsing and metadata validation
# ---------------------------------------------------------------------------


def _parse_front_matter(normalized_source: str, *, source_file: str) -> tuple[dict[str, Any], str]:
    """Parse YAML front matter and return ``(raw_metadata, body)``."""

    lines = normalized_source.splitlines()

    if not lines or lines[0].strip() != "---":
        raise PolicyValidationError(
            f"{source_file}: policy must begin with YAML front matter delimited by '---'."
        )

    closing_index: int | None = None

    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            closing_index = index
            break

    if closing_index is None:
        raise PolicyValidationError(
            f"{source_file}: YAML front matter is missing its closing '---' delimiter."
        )

    yaml_text = "\n".join(lines[1:closing_index]).strip()

    if not yaml_text:
        raise PolicyValidationError(f"{source_file}: YAML front matter cannot be empty.")

    try:
        loaded = yaml.safe_load(yaml_text)
    except yaml.YAMLError as exc:
        raise PolicyValidationError(
            f"{source_file}: invalid YAML front matter: {exc}"
        ) from exc

    if not isinstance(loaded, Mapping):
        raise PolicyValidationError(
            f"{source_file}: YAML front matter must be a key-value mapping."
        )

    raw_metadata: dict[str, Any] = {}

    for raw_key, value in loaded.items():
        if not isinstance(raw_key, str) or not raw_key.strip():
            raise PolicyValidationError(
                f"{source_file}: every YAML metadata key must be a non-empty string."
            )

        key = raw_key.strip()

        if key in raw_metadata:
            # This is mainly defensive.  PyYAML normally resolves duplicate
            # scalar keys before returning the mapping.
            raise PolicyValidationError(
                f"{source_file}: duplicate YAML metadata key {key!r}."
            )

        raw_metadata[key] = value

    body = "\n".join(lines[closing_index + 1 :]).strip()

    if not body:
        raise PolicyValidationError(f"{source_file}: policy body cannot be empty.")

    return raw_metadata, body


def _normalized_metadata_key(key: str) -> str:
    return key.strip().casefold().replace("-", "_").replace(" ", "_")


def _is_forbidden_metadata_key(key: str) -> bool:
    normalized = _normalized_metadata_key(key)

    if normalized in DERIVED_METADATA_FIELDS or normalized in FORBIDDEN_PATH_FIELDS:
        return True

    return normalized.endswith(
        (
            "_path",
            "_filepath",
            "_file_path",
            "_filename",
            "_file_name",
            "_directory",
            "_folder",
        )
    )


def _validate_no_yaml_path_fields(raw_metadata: Mapping[str, Any], *, source_file: str) -> None:
    forbidden = sorted(
        key for key in raw_metadata if _is_forbidden_metadata_key(key)
    )

    if forbidden:
        raise PolicyValidationError(
            f"{source_file}: filesystem or derived metadata fields are not allowed in YAML: "
            f"{', '.join(forbidden)}. source_file and hashes are generated by application code."
        )


def _normalize_scalar(value: object, *, field_name: str, source_file: str) -> str:
    if value is None:
        raise PolicyValidationError(
            f"{source_file}: required metadata field {field_name!r} cannot be null."
        )

    if isinstance(value, bool) or isinstance(value, (Mapping, list, tuple, set)):
        raise PolicyValidationError(
            f"{source_file}: required metadata field {field_name!r} must be a scalar value."
        )

    normalized = str(value).strip()

    if not normalized:
        raise PolicyValidationError(
            f"{source_file}: required metadata field {field_name!r} cannot be empty."
        )

    return normalized


def _parse_iso_date(value: object, *, field_name: str, source_file: str) -> tuple[str, date]:
    normalized = normalize_date(value)

    if not normalized:
        raise PolicyValidationError(
            f"{source_file}: required metadata field {field_name!r} cannot be empty."
        )

    try:
        parsed = date.fromisoformat(normalized)
    except ValueError as exc:
        raise PolicyValidationError(
            f"{source_file}: {field_name} must use ISO date format YYYY-MM-DD; "
            f"received {normalized!r}."
        ) from exc

    # ``date.fromisoformat`` accepts only date-shaped inputs in supported Python
    # versions, but this equality also guarantees a canonical stored value.
    canonical = parsed.isoformat()

    if normalized != canonical:
        raise PolicyValidationError(
            f"{source_file}: {field_name} must be the canonical date {canonical!r}."
        )

    return canonical, parsed


def _build_stored_metadata(
    raw_metadata: Mapping[str, Any],
    *,
    source_file: str,
    source_hash: str,
) -> dict[str, str]:
    missing = [field for field in REQUIRED_METADATA_FIELDS if field not in raw_metadata]

    if missing:
        raise PolicyValidationError(
            f"{source_file}: missing required metadata: {', '.join(missing)}."
        )

    _validate_no_yaml_path_fields(raw_metadata, source_file=source_file)

    document_id = _normalize_scalar(
        raw_metadata["document_id"],
        field_name="document_id",
        source_file=source_file,
    )

    if DOCUMENT_ID_PATTERN.fullmatch(document_id) is None:
        raise PolicyValidationError(
            f"{source_file}: document_id must use lowercase snake_case and begin with a letter; "
            f"received {document_id!r}."
        )

    title = _normalize_scalar(
        raw_metadata["title"], field_name="title", source_file=source_file
    )
    version = _normalize_scalar(
        raw_metadata["version"], field_name="version", source_file=source_file
    )
    owner = _normalize_scalar(
        raw_metadata["owner"], field_name="owner", source_file=source_file
    )
    product = _normalize_scalar(
        raw_metadata["product"], field_name="product", source_file=source_file
    )
    policy_type = _normalize_scalar(
        raw_metadata["policy_type"], field_name="policy_type", source_file=source_file
    )

    status = _normalize_scalar(
        raw_metadata["status"], field_name="status", source_file=source_file
    ).casefold()

    if status != "approved":
        raise PolicyValidationError(
            f"{source_file}: status must equal 'approved'; received {status!r}."
        )

    jurisdiction = _normalize_scalar(
        raw_metadata["jurisdiction"],
        field_name="jurisdiction",
        source_file=source_file,
    ).casefold()

    if jurisdiction != "fictional_prototype":
        raise PolicyValidationError(
            f"{source_file}: jurisdiction must equal 'fictional_prototype'; "
            f"received {jurisdiction!r}."
        )

    effective_date_text, effective_date_value = _parse_iso_date(
        raw_metadata["effective_date"],
        field_name="effective_date",
        source_file=source_file,
    )
    review_date_text, review_date_value = _parse_iso_date(
        raw_metadata["review_date"],
        field_name="review_date",
        source_file=source_file,
    )

    if effective_date_value > review_date_value:
        raise PolicyValidationError(
            f"{source_file}: effective_date cannot be after review_date."
        )

    if not SHA256_PATTERN.fullmatch(source_hash):
        raise PolicyValidationError(
            f"{source_file}: generated source_hash is not a valid SHA-256 digest."
        )

    # Only reviewed fields are copied.  Unknown non-path YAML fields are ignored
    # rather than entering Chroma metadata accidentally.
    return {
        "document_id": document_id,
        "source_file": source_file,
        "title": title,
        "version": version,
        "effective_date": effective_date_text,
        "review_date": review_date_text,
        "owner": owner,
        "status": status,
        "policy_type": policy_type,
        "product": product,
        "jurisdiction": jurisdiction,
        "source_hash": source_hash,
    }


# ---------------------------------------------------------------------------
# Public loading APIs
# ---------------------------------------------------------------------------


def load_policy_file(path: str | Path) -> PolicyDocument:
    """Load and validate one Markdown policy file.

    The input path may be absolute or relative.  Only its basename is copied
    into stored metadata.
    """

    source_path = Path(path).expanduser()

    if not source_path.exists():
        raise PolicyValidationError(
            f"{source_path.name or str(source_path)}: policy file does not exist."
        )

    if not source_path.is_file():
        raise PolicyValidationError(
            f"{source_path.name or str(source_path)}: policy path is not a file."
        )

    if source_path.suffix.casefold() != ".md":
        raise PolicyValidationError(
            f"{source_path.name}: policy file must use the .md extension."
        )

    source_file = source_path.name

    if not source_file or "/" in source_file or "\\" in source_file:
        raise PolicyValidationError("Policy source filename is not a safe basename.")

    try:
        raw_source = source_path.read_text(encoding="utf-8-sig")
    except UnicodeDecodeError as exc:
        raise PolicyValidationError(
            f"{source_file}: policy file must be valid UTF-8 text."
        ) from exc
    except OSError as exc:
        raise PolicyValidationError(
            f"{source_file}: unable to read policy file: {exc}"
        ) from exc

    normalized_source = normalize_policy_source(raw_source)
    source_hash = compute_source_hash(normalized_source)
    raw_metadata, body = _parse_front_matter(
        normalized_source,
        source_file=source_file,
    )
    stored_metadata = _build_stored_metadata(
        raw_metadata,
        source_file=source_file,
        source_hash=source_hash,
    )

    return PolicyDocument(
        source_path=source_path.resolve(),
        body=body,
        metadata=MappingProxyType(stored_metadata),
        normalized_source=normalized_source,
    )


def validate_unique_document_ids(documents: Iterable[PolicyDocument]) -> None:
    """Reject duplicate document IDs across a policy collection."""

    seen: dict[str, str] = {}

    for document in documents:
        previous_file = seen.get(document.document_id)

        if previous_file is not None:
            raise DuplicatePolicyDocumentError(
                "Duplicate document_id "
                f"{document.document_id!r} found in {previous_file!r} "
                f"and {document.source_file!r}."
            )

        seen[document.document_id] = document.source_file


def load_policy_files(paths: Iterable[str | Path]) -> tuple[PolicyDocument, ...]:
    """Load multiple policies and enforce unique document IDs."""

    path_list = tuple(Path(path) for path in paths)

    if not path_list:
        raise PolicyValidationError("No policy files were supplied.")

    documents = tuple(load_policy_file(path) for path in path_list)
    validate_unique_document_ids(documents)

    return documents


def load_policy_directory(directory: str | Path) -> tuple[PolicyDocument, ...]:
    """Load every top-level Markdown policy in a directory.

    Files are processed in case-insensitive filename order so validation and
    ingestion are deterministic across runs.
    """

    policies_dir = Path(directory).expanduser()

    if not policies_dir.exists():
        raise PolicyValidationError("Policy directory does not exist.")

    if not policies_dir.is_dir():
        raise PolicyValidationError("Policy directory path is not a directory.")

    paths = sorted(
        (
            path
            for path in policies_dir.iterdir()
            if path.is_file() and path.suffix.casefold() == ".md"
        ),
        key=lambda path: path.name.casefold(),
    )

    if not paths:
        raise PolicyValidationError("Policy directory contains no Markdown files.")

    return load_policy_files(paths)


# A descriptive alias for ingestion code.
load_approved_policies = load_policy_directory


__all__ = [
    "DERIVED_METADATA_FIELDS",
    "DuplicatePolicyDocumentError",
    "PolicyDocument",
    "PolicyValidationError",
    "REQUIRED_METADATA_FIELDS",
    "compute_content_hash",
    "compute_source_hash",
    "load_approved_policies",
    "load_policy_directory",
    "load_policy_file",
    "load_policy_files",
    "normalize_chunk_content",
    "normalize_date",
    "normalize_policy_source",
    "validate_unique_document_ids",
]
